#!/bin/env bash
# ClusterHAT controller

GPIO_BASE_ADDRESS="21"
RAMPUP_DELAY=2

CONTROLLER_MODE=
CONTROLLER_DEVICES=

error() {
  echo "$*" 1>&2
}

fatal() {
  error "$*"
  exit -1
}

gpio_enable() {
  local address="$1"
  gpio write "$address" 1
}

gpio_disable() {
  local address="$1"
  gpio write "$address" 0
}

led_enable() {
  gpio_enable "$GPIO_BASE_ADDRESS"
}

led_disable() {
  gpio_disable "$GPIO_BASE_ADDRESS"
}

pizero_enable() {
  local index="$1"

  if [[ $index < 1 || $index > 4 ]]; then
    fatal "Invalid pizero index value: '$index'"
  fi

  echo "Turning on P$index"
  gpio_enable "$(($GPIO_BASE_ADDRESS + $index))"
}

pizero_disable() {
  local index="$1"

  if [[ $index < 1 || $index > 4 ]]; then
    fatal "Invalid pizero index value: '$index'"
  fi

  echo "Turning off P$index"
  gpio_disable "$(($GPIO_BASE_ADDRESS + $index))"
}

usage() {
  echo
  echo "Usage: $0 <action> [<device>] [<device>] ..."
  echo "  action = on / off"
  echo "  device = all / p1 / p2 / p3 / p4"
  echo
  echo "Examples:"
  echo "  $0 on p1 p3 # Turns on P1 and P3"
  echo "  $0 off all # Turns off P1-4"
}

parse_arguments() {
  if [[ $# < 2 ]]; then
    usage
    exit 1
  fi

  if [[ ${1,,} =~ on|off ]]; then
    CONTROLLER_MODE=${1,,}
  else
    error "Unknown mode: '$1'"
    usage
    exit 2
  fi

  shift

  while (("$#")); do
    local arg=${1,,}
    if [[ $arg == "all" ]]; then
      CONTROLLER_DEVICES="1 2 3 4"
      break
    elif [[ $arg =~ ^p([0-9])$ ]]; then
      if [[ ${BASH_REMATCH[1]} < 1 || ${BASH_REMATCH[1]} > 4 ]]; then
        error "Invalid pizero identifier: '$1'"
        usage
        exit 3
      fi
      CONTROLLER_DEVICES="$CONTROLLER_DEVICES ${BASH_REMATCH[1]}"
    else
      error "Invalid pizero identifier: '$1'"
      usage
      exit 4
    fi
    shift
  done

  CONTROLLER_DEVICES=$(tr " " "\n" <<< "$CONTROLLER_DEVICES" | sort -u)
}

run() {
  # Turn "Alert" LED on whilst we're running
  led_enable

  for device in $CONTROLLER_DEVICES; do
    if [[ $CONTROLLER_MODE == "on" ]]; then
      pizero_enable "$device"
    else
      pizero_disable "$device"
    fi

    if [[ $(wc -w <<< "$CONTROLLER_DEVICES") > 1 ]]; then
      sleep "$RAMPUP_DELAY"
    fi
  done

  # Turn "Alert" LED off
  led_disable
}

parse_arguments $*
run
